<project>

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.mvp</groupId>
    <artifactId>alex</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/>
    </parent>

    <packaging>pom</packaging>

    <modules>
        <module>markdown</module>
        <module>mcp</module>
        <module>intelligence</module>
        <module>app</module>
    </modules>



</project>