spring.application.name=markdown
vault.path = ./vault

spring.datasource.url=jdbc:postgresql://localhost:5433/postgres?serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver