spring.application.name=markdown
alexandria.vault.path = C:/Users/happie/Documents/Alexandria-vault

spring.datasource.url=jdbc:postgresql://localhost:5433/alex-test?serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always